<?php
// This file is part of Moodle - http://moodle.org/

defined('MOODLE_INTERNAL') || die();

$string['pluginname'] = 'AI Feedback';
$string['enabled'] = 'Enable automatic AI feedback';
$string['enabled_help'] = 'If enabled, the plugin will automatically generate feedback and grades using OpenAI when a student submits their work.';
$string['rubricfile'] = 'Evaluation rubric (PDF)';
$string['rubricfile_help'] = 'Upload a PDF with the evaluation rubric that AI will use to evaluate student submissions.';
$string['apikey'] = 'OpenAI API Key';
$string['apikey_help'] = 'Your OpenAI API Key. If not provided, the global site configuration will be used.';
$string['model'] = 'AI Model';
$string['model_help'] = 'OpenAI model to use (gpt-3.5-turbo recommended for costs, gpt-4 for better quality).';
$string['processing'] = 'Generating AI feedback...';
$string['error_processing'] = 'Error processing submission with AI';
$string['error_nofile'] = 'Submission file not found';
$string['error_norubric'] = 'No evaluation rubric has been configured for this assignment';
$string['error_noapikey'] = 'No OpenAI API Key has been configured';
$string['error_openai'] = 'OpenAI API error: {$a}';
$string['unsupportedfiletype'] = 'Unsupported file type. Use TXT, PDF or DOCX';
$string['ai_feedback_generated'] = 'Feedback automatically generated by AI';
$string['rubric_content'] = 'Extracted rubric content';
$string['global_apikey'] = 'Global OpenAI API Key';
$string['global_apikey_desc'] = 'OpenAI API Key to be used by default if not specified in individual assignments.';
$string['global_model'] = 'Default AI model';
$string['global_model_desc'] = 'OpenAI model to use by default.';
$string['privacy:metadata:assignfeedback_ai_config'] = 'AI feedback plugin configuration';
$string['privacy:metadata:assignfeedback_ai_config:assignmentid'] = 'Assignment ID';
$string['privacy:metadata:assignfeedback_ai_config:enabled'] = 'Whether AI feedback is enabled';
$string['privacy:metadata:assignfeedback_ai_config:apikey'] = 'Encrypted OpenAI API Key';
$string['privacy:metadata:openai'] = 'The plugin sends submission content to OpenAI to generate feedback';
$string['privacy:metadata:openai:submission'] = 'Student submission content';
$string['privacy:metadata:openai:rubric'] = 'Evaluation rubric';
$string['privacy:metadata:openai:taskdescription'] = 'Assignment description';
